apiVersion: v1
kind: ConfigMap
metadata:
  name: online-shop-config
  namespace: online-shop-prod
data:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "5173"
  VITE_HOST: "0.0.0.0"
  DATABASE_NAME: "rds-database"
  CDD_VERSION: "10.2.0.4"
  AIS_VERSION: "10.4.0.0"
  SAP_VERSION: "10.0.0.0"
  IFM: 00.00.00.00 #DEMO_BRANCH


  #tum sbki mkc
